server.port=8081
spring.application.name=user-service
user.service.message=User Service is running from COnfig Server

spring.datasource.username=root
spring.datasource.password={cipher}102ba7de058b75ff19a7b4bfcac5d3c7a892af883fc54ce6669ef925b80d596b